// Code generated by options-gen. DO NOT EDIT.

package proxy

import (
	"net/http"
	"net/url"

	"k8s.io/apiserver/plugin/pkg/authenticator/token/oidc"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	oidcAuthenticator oidc.AuthenticatorTokenWithHealthCheck,
	transport http.RoundTripper,
	targetURL *url.URL,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.oidcAuthenticator = oidcAuthenticator
	o.transport = transport
	o.targetURL = targetURL

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	return nil
}
